<?php

return [
    '' => 'Frontend/default/index',
    'user' => 'Dashbord/user/index',
    'login' => 'Dashbord/default/login',
    'logout' => 'Dashbord/default/logout',
    'signup' => 'Dashbord/default/signup',
    'role' => 'Dashbord/role/index',
    'password' => 'Dashbord/user/password',
    'update' => 'Dashbord/user/update',
    'delete' => 'Dashbord/user/delete',
    'shop' => 'Shop/shop/index',
    's/<id:\d+>' => 'Frontend/default/shop',
    'product' => 'Shop/product/index',
    'group' => 'Dashbord/group/index',
    'category' => 'Dashbord/category/index',
    'categoryItem' => 'Dashbord/item/index',
    'details' => 'Shop/details/index',
    'detailsCreate' => 'Shop/details/create',
    'detailsUpdate' => 'Shop/details/update',
    'detailsDelete' => 'Shop/details/delete',
    'items' => 'Shop/detailsitem/index',
    'itemUpdate/<id:\d+>' => 'Shop/detailsitem/update',
    'itemCreate' => 'Shop/detailsitem/create',
    'itemDelete' => 'Shop/detailsitem/delete',
    'valueUpdate' => 'Shop/detailsvalue/update',
    'valueCreate' => 'Shop/detailsvalue/create',
    'valueDelete' => 'Shop/detailsvalue/delete',
];
